services:
    server:
        container_name: educ_server
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.server
        runtime: nvidia
        ports:
            - 7256:8000
        environment:
            HF_HOME: '/root/.cache/huggingface'
            LLM_API_KEY: ${LLM_API_KEY}
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
            DEFAULT_ADMIN_EMAIL: ${DEFAULT_ADMIN_EMAIL}
            DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD}
            SQLALCHEMY_URL: ${SQLALCHEMY_URL}
            SIGN_SECRET_KEY: ${SIGN_SECRET_KEY}
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - postgres
        volumes:
            - ~/.cache/huggingface:/root/.cache/huggingface
        command: uvicorn server.main:app --host 0.0.0.0 --port 8000

    client:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.client
        ports:
            - '3000:80'
        networks:
            - postgres
        depends_on:
            - server
        restart: always

    postgres:
        container_name: educ_pg
        image: pgvector/pgvector:pg15
        command:
            - 'postgres'
            - '-c'
            - 'max_connections=50'
            - '-c'
            - 'shared_buffers=1GB'
            - '-c'
            - 'effective_cache_size=4GB'
            - '-c'
            - 'work_mem=16MB'
            - '-c'
            - 'maintenance_work_mem=512MB'
            - '-c'
            - 'random_page_cost=1.1'
            - '-c'
            - 'temp_file_limit=10GB'
            - '-c'
            - 'log_min_duration_statement=200ms'
            - '-c'
            - 'idle_in_transaction_session_timeout=10s'
            - '-c'
            - 'lock_timeout=1s'
            - '-c'
            - 'statement_timeout=60s'
            - '-c'
            - 'shared_preload_libraries=pg_stat_statements'
            - '-c'
            - 'pg_stat_statements.max=10000'
            - '-c'
            - 'pg_stat_statements.track=all'
        environment:
            PGDATA: '/var/lib/postgresql/data/pgdata'
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - init-database:/docker-entrypoint-initdb.d
            - educ-data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U educ-user -d educ-db']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 4G
        networks:
            - postgres

volumes:
    educ-data:
    init-database:

networks:
    postgres:
        driver: bridge
