# 1. Build stage
FROM node:20-alpine AS builder

WORKDIR /workspace

COPY client/package.json client/package-lock.json ./
RUN npm install --omit=dev

COPY client/ .
RUN npm run build

# 2. Serve stage
FROM nginx:alpine AS production

RUN rm -rf /etc/nginx/conf.d/default.conf
COPY client/nginx.conf /etc/nginx/conf.d

COPY --from=builder /workspace/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
