# DEV/TEST/PROD
env: 'TEST'

# Cache store for embeddings
embeddings_model_name: 'deepvk/USER-bge-m3'
embeddings_cache_path: './benchmark/data/cache/embeddings'

# LLM API configuration
llm_model_name: 'meta-llama/Llama-3.3-70B-Instruct-Turbo-Free'
llm_api_base: 'https://api.together.xyz/v1'

# Rate limiter for LLM API
llm_requests_per_second: 1
llm_check_every_n_seconds: 1
llm_max_bucket_size: 1

# JWT for protected routes
jwt_algorithm: 'HS256'
jwt_token_expires_minutes: 3000

# Local file storage settings
file_storage_path:
    TEST: './file-storage'
    PROD: '/var/lib/file-storage' # Path in container

max_files_per_user: 10
max_file_size: 15
