@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

skinparam wrapWidth 300
LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

Person(client, "Пользователь")
System(app, "Веб-приложение", "Помогает пользователю в обучении.")
System_Ext(llm_api, "Большая языковая модель", "Обрабатывает части пайплайна RAG.")

Rel(client, app, "Отправляет вопросы/файлы.")
Rel(app, llm_api, "Генерация ответов")

@enduml
