name: Educ application

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

env:
    COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
    test:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5
              with:
                  version: '0.7.2'

            - name: Enable caching
              uses: astral-sh/setup-uv@v5
              with:
                  enable-cache: true

            - name: Install the project
              run: uv sync --locked --all-extras --dev

            - name: Run tests with coverage
              run: uv run pytest --cov=server --cov-report=term --cov-report=xml

            - name: Upload coverage to Coveralls
              uses: coverallsapp/github-action@v2

    build:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Stop previous containers
              run: docker compose -f ./docker/compose.prod.yml down

            - name: Write .env file
              run: |
                echo "LLM_API_KEY=${{ secrets.LLM_API_KEY }}" >> .env
                echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
                echo "DEFAULT_ADMIN_EMAIL=${{ secrets.DEFAULT_ADMIN_EMAIL }}" >> .env
                echo "DEFAULT_ADMIN_PASSWORD=${{ secrets.DEFAULT_ADMIN_PASSWORD }}" >> .env
                echo "SIGN_SECRET_KEY=${{ secrets.SIGN_SECRET_KEY }}" >> .env
                echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
                echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
                echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
            
            - name: Build and run containers
              run: |
                cat .env
                docker compose -f ./docker/compose.prod.yml --env-file .env up -d --build
